spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
      ssl.truststore.certificates: ${KAFKA_SSL_TRUSTSTORE_CERTIFICATES:}
      ssl.truststore.type: ${KAFKA_SSL_TRUSTSTORE_TYPE:PEM}
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.rishav.commerce.events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_BASE_URL:http://127.0.0.1:8081}/realms/commerce
  datasource:
    url: ${ORDER_DATABASE_URL:jdbc:postgresql://${ORDER_DATABASE_HOST:127.0.0.1}:${ORDER_DATABASE_PORT:5433}/${ORDER_DATABASE_NAME:order_db}}
    username: ${ORDER_DATABASE_USER:commerce}
    password: ${ORDER_DATABASE_PASSWORD:commerce}
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
logging:
  file.name: ${LOG_FILE:../logs/order-service.log}
server:
  port: ${PORT:8082}
