import { FormEvent, useEffect, useState } from 'react'
import { authorizationHeader, initializeAuth, signIn, signOut, signUp } from './auth'
const API=`${(import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8080').replace(/\/$/, '')}/api/v1`; const FLOW=['PENDING_INVENTORY','INVENTORY_RESERVED','PAID']; type Product={id:string;name:string;price:number}; type Order={id:string;status:string;totalAmount:number};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())
export default function App(){const[products,setProducts]=useState<Product[]>([]),[productId,setProductId]=useState(''),[signed,setSigned]=useState(false),[message,setMessage]=useState('Loading catalog…'),[order,setOrder]=useState<Order|null>(null),[history,setHistory]=useState<Order[]>([])
 const loadHistory=async()=>{try{const r=await fetch(`${API}/orders`,{headers:await authorizationHeader()});if(r.ok)setHistory(await r.json())}catch{}}
 useEffect(()=>{initializeAuth().then(ok=>{setSigned(ok);if(ok)void loadHistory()});fetch(`${API}/products`).then(r=>r.json()).then((x:Product[])=>{setProducts(x);setProductId(x[0]?.id??'');setMessage('Choose a product and create an order.')})},[])
 useEffect(()=>{if(!order||['PAID','OUT_OF_STOCK'].includes(order.status))return;let stop=false;const f=async()=>{try{const r=await fetch(`${API}/orders/${order.id}`,{headers:await authorizationHeader()});if(r.ok&&!stop){const x=await r.json();setOrder(x);setMessage(x.status==='INVENTORY_RESERVED'?'Inventory reserved. Payment is ready.':`Workflow update: ${label(x.status)}.`)}}catch{}};void f();const t=setInterval(f,1500);return()=>{stop=true;clearInterval(t)}},[order?.id,order?.status])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),p=products.find(x=>x.id===productId);try{const r=await fetch(`${API}/orders`,{method:'POST',headers:{'Content-Type':'application/json',...await authorizationHeader()},body:JSON.stringify({productId,quantity:Number(d.get('quantity')),unitPrice:p?.price})});if(!r.ok)throw Error('Order request failed');const x=await r.json();setOrder({id:x.orderId,status:'PENDING_INVENTORY',totalAmount:p?.price??0});setMessage('Order accepted. Waiting for inventory…');void loadHistory()}catch(err){setMessage(err instanceof Error?err.message:'Unable to create order')}}
 const pay=async()=>{if(!order)return;try{const h=await authorizationHeader(),c=await fetch(`${API}/payments/${order.id}/checkout`,{headers:h}).then(r=>r.json());if(!(window as any).Razorpay)await new Promise<void>((ok,bad)=>{const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>ok();s.onerror=()=>bad(Error('Could not load Razorpay'));document.body.appendChild(s)});new (window as any).Razorpay({key:c.keyId,order_id:c.razorpayOrderId,name:'EventFlow Commerce',description:'Test Mode payment',theme:{color:'#25b9ee'},handler:async(x:any)=>{const r=await fetch(`${API}/payments/${order.id}/verify`,{method:'POST',headers:{'Content-Type':'application/json',...await authorizationHeader()},body:JSON.stringify({razorpayOrderId:x.razorpay_order_id,razorpayPaymentId:x.razorpay_payment_id,razorpaySignature:x.razorpay_signature})});if(!r.ok)throw Error('Payment verification failed');setMessage('Payment verified. Updating order…')}}).open()}catch(e){setMessage(e instanceof Error?e.message:'Unable to open Razorpay')}}
 const selected=products.find(x=>x.id===productId),step=order?FLOW.indexOf(order.status):-1;return <div className="shell"><header><a className="brand"><b>EF</b>EventFlow <strong>Commerce</strong></a><div className="actions">{signed?<button className="ghost" onClick={signOut}>Sign out</button>:<><button className="ghost" onClick={signUp}>Create account</button><button onClick={signIn}>Sign in</button></>}</div></header><main><section className="intro"><div><p className="eyebrow">PRODUCT CATALOG</p><h1>Order command center</h1><p>Choose a catalog product, then send it through the event-driven workflow.</p></div></section><section className="workspace"><form onSubmit={submit}><p className="eyebrow">NEW REQUEST</p><h2>Create an order</h2><label>Product<select value={productId} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option value={p.id} key={p.id}>{p.name} · ${p.price}</option>)}</select></label><div className="fields"><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Unit price<input value={selected?.price??''} readOnly/></label></div><button disabled={!signed}>Create order →</button><output><i/>{message}</output>{order&&<section className="tracker"><div className="tracker-head"><div><p className="eyebrow">LIVE ORDER TRACKER</p><strong>{label(order.status)}</strong></div><code>#{order.id.slice(0,8)}</code></div><ol>{FLOW.map((s,i)=><li className={i<=step?'complete':''} key={s}><i>{i<step?'✓':i+1}</i><span>{label(s)}</span></li>)}</ol>{order.status==='INVENTORY_RESERVED'&&<button type="button" onClick={pay}>Pay with Razorpay (Test)</button>}</section>}</form><aside><p className="eyebrow">CATALOG</p><h2>Available products</h2>{products.map(p=><div className="route" key={p.id}><small>{p.name}</small><p>${p.price.toFixed(2)} <b>{p.id===productId?'Selected':'Available'}</b></p></div>)}<section className="history"><p className="eyebrow">RECENT ORDERS</p>{history.map(o=><div className="history-row" key={o.id}><code>#{o.id.slice(0,8)}</code><span>{label(o.status)}</span><b>${o.totalAmount.toFixed(2)}</b></div>)}</section></aside></section></main><footer><b>EventFlow Commerce</b><span>Gateway <code>8080</code></span></footer></div>}
