spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.rishav.commerce.events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/realms/commerce}
  datasource:
    url: ${ORDER_DATABASE_URL:jdbc:postgresql://127.0.0.1:5433/order_db}
    username: ${ORDER_DATABASE_USER:commerce}
    password: ${ORDER_DATABASE_PASSWORD:commerce}
  jpa:
    hibernate.ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
server:
  port: 8082
