server:
  port: ${PORT:8084}
spring:
 application: { name: product-catalog }
 datasource:
  url: ${PRODUCT_DATABASE_URL:jdbc:postgresql://${PRODUCT_DATABASE_HOST:127.0.0.1}:${PRODUCT_DATABASE_PORT:5433}/${PRODUCT_DATABASE_NAME:product_db}}
  username: ${PRODUCT_DATABASE_USER:commerce}
  password: ${PRODUCT_DATABASE_PASSWORD:commerce}
 jpa: { hibernate: { ddl-auto: validate } }
 flyway: { enabled: true }
management: { endpoints: { web: { exposure: { include: health,info,metrics,prometheus } } } }
